apiUrl: "api.lago.dev"
frontUrl: "front.lago.dev"
job:
  migrate:
    loadSchema: true

api:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"
worker:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

eventsWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

clockWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

pdf:
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

billingWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

pdfWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

webhookWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"

paymentWorker:
  enabled: true
  resources:
    requests:
      memory: '512Mi'
      cpu: "200m"
