{{- if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  labels:
    {{ include "lago.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  policyTypes:
  - Egress
  - Ingress
  egress:
  {{- with .Values.global.networkPolicy }}
  {{- toYaml .egress | nindent 4 }}
  {{- end }}
  ingress:
  {{- with .Values.global.networkPolicy }}
  {{- toYaml .ingress | nindent 4 }}
  {{- end }}
{{- end }}
