{{ if not .Values.global.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-watch-services
  labels:
    app: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  - "batch"
  resources:
    - pods
    - jobs
  resourceNames:
    {{ if .Values.minio.enabled }}
    - {{ .Release.Name }}-minio-0
    {{ end}}
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-watch-services
  labels:
    app: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccountName | default (printf "%s-serviceaccount" .Release.Name) }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-watch-services
  apiGroup: ""
