apiVersion: v2
appVersion: "1.32.4"
description: the Lago open source billing app
name: lago
version: 1.27.0
dependencies:
  - name: minio
    version: "5.2.0"
    repository: https://charts.min.io/
    condition: minio.enabled
